# step 1- EDA

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("used_car_price_dataset_extended.csv")

In [3]:
data.head()

,make_year,mileage_kmpl,engine_cc,fuel_type,owner_count,price_usd,brand,transmission,color,service_history,accidents_reported,insurance_valid
0,2001,8.17,4000,Petrol,4,8587.64,Chevrolet,Manual,White,NaN,0,No
1,2014,17.59,1500,Petrol,4,5943.50,Honda,Manual,Black,NaN,0,Yes
2,2023,18.09,2500,Diesel,5,9273.58,BMW,Automatic,Black,Full,1,Yes
3,2009,11.28,800,Petrol,1,6836.24,Hyundai,Manual,Blue,Full,0,Yes
4,2005,12.23,1000,Petrol,2,4625.79,Nissan,Automatic,Red,Full,0,Yes

In [4]:
data.tail()

,make_year,mileage_kmpl,engine_cc,fuel_type,owner_count,price_usd,brand,transmission,color,service_history,accidents_reported,insurance_valid
9995,1996,15.25,1500,Petrol,2,5498.71,Hyundai,Manual,Silver,NaN,0,Yes
9996,1997,14.45,5000,Diesel,1,9588.31,Honda,Manual,Gray,Full,0,Yes
9997,2002,19.41,1000,Diesel,4,4557.10,Kia,Manual,Black,Full,0,Yes
9998,2005,12.95,4000,Petrol,5,7413.59,BMW,Automatic,Blue,Full,0,Yes
9999,2007,18.81,5000,Petrol,1,11634.09,BMW,Automatic,Silver,Full,0,Yes

In [5]:
data.describe()

,make_year,mileage_kmpl,engine_cc,owner_count,price_usd,accidents_reported
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2009.206900,17.960753,2287.130000,3.003500,7179.754532,0.492200
std,8.373858,5.025486,1291.276927,1.418904,2795.270940,0.694109
min,1995.000000,5.000000,800.000000,1.000000,1000.000000,0.000000
25%,2002.000000,14.540000,1200.000000,2.000000,5176.547500,0.000000
50%,2009.000000,17.970000,1800.000000,3.000000,6961.260000,0.000000
75%,2016.000000,21.352500,3000.000000,4.000000,8993.732500,1.000000
max,2023.000000,35.000000,5000.000000,5.000000,17647.630000,5.000000

In [6]:
print(data.isnull().sum())

make_year                0
mileage_kmpl             0
engine_cc                0
fuel_type                0
owner_count              0
price_usd                0
brand                    0
transmission             0
color                    0
service_history       2038
accidents_reported       0
insurance_valid          0
dtype: int64

In [7]:
corr_matrix = data.corr(numeric_only=True)

print(corr_matrix["price_usd"].sort_values(ascending=False))

price_usd             1.000000
engine_cc             0.678161
make_year             0.432603
mileage_kmpl          0.211971
accidents_reported   -0.001461
owner_count          -0.262266
Name: price_usd, dtype: float64

In [8]:
data.columns

Index(['make_year', 'mileage_kmpl', 'engine_cc', 'fuel_type', 'owner_count',
       'price_usd', 'brand', 'transmission', 'color', 'service_history',
       'accidents_reported', 'insurance_valid'],
      dtype='object')

In [9]:
dataFeatures = data.drop("price_usd", axis=1)

In [10]:
dataLabels = data["price_usd"]

In [11]:
dataFeatures.head()

,make_year,mileage_kmpl,engine_cc,fuel_type,owner_count,brand,transmission,color,service_history,accidents_reported,insurance_valid
0,2001,8.17,4000,Petrol,4,Chevrolet,Manual,White,NaN,0,No
1,2014,17.59,1500,Petrol,4,Honda,Manual,Black,NaN,0,Yes
2,2023,18.09,2500,Diesel,5,BMW,Automatic,Black,Full,1,Yes
3,2009,11.28,800,Petrol,1,Hyundai,Manual,Blue,Full,0,Yes
4,2005,12.23,1000,Petrol,2,Nissan,Automatic,Red,Full,0,Yes

In [12]:
dataLabels.head()

0    8587.64
1    5943.50
2    9273.58
3    6836.24
4    4625.79
Name: price_usd, dtype: float64

#  step 2-Split into training and test sets

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    dataFeatures,
    dataLabels,
    test_size=0.2,
    random_state=42
)

In [14]:
# X_train → 80% of the FEATURES
# y_train → 80% of the LABELS

# X_test  → 20% of the FEATURES
# y_test  → 20% of the LABELS

#During Training model.fit(X_train, y_train)

#During testing predictions = model.predict(X_test)

In [15]:

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (8000, 11)
X_test shape: (2000, 11)

In [16]:
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

y_train shape: (8000,)
y_test shape: (2000,)

In [17]:
num_attributes = X_train.select_dtypes(include=["int64","float64"]).columns.tolist()

In [21]:
cat_attributes = X_train.select_dtypes(include=["object"]).columns.tolist()

In [22]:
num_attributes

['make_year', 'mileage_kmpl', 'engine_cc', 'owner_count', 'accidents_reported']

In [23]:
cat_attributes

['fuel_type',
 'brand',
 'transmission',
 'color',
 'service_history',
 'insurance_valid']

# step 4-Now create the numerical & Categorical Pipeline:

In [25]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [26]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("standard_scaler", StandardScaler())
])

print(num_pipeline)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('standard_scaler', StandardScaler())])

In [27]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("one_hot_encoder", OneHotEncoder(handle_unknown="ignore"))
])

print(cat_pipeline)

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('one_hot_encoder', OneHotEncoder(handle_unknown='ignore'))])

# Step 6: combine the numerical and categorical pipelines.

In [29]:
full_pipeline = ColumnTransformer([
    ("num",num_pipeline, num_attributes),
    ("cat",cat_pipeline, cat_attributes)
])
print(full_pipeline)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standard_scaler',
                                                  StandardScaler())]),
                                 ['make_year', 'mileage_kmpl', 'engine_cc',
                                  'owner_count', 'accidents_reported']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('one_hot_encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['fuel_type', 'brand', 'transmission', 'color',
                                  'service_history', 'insurance_valid'])])

# Step 7 — Transform the training data

In [30]:
data_prepared = full_pipeline.fit_transform(X_train)

print(data_prepared.shape)
print(data_prepared)

(8000, 30)
[[-0.8608841  -1.64425297 -0.37968173 ...  1.          1.
   0.        ]
 [-0.62245333 -0.36814553 -0.61228828 ...  0.          1.
   0.        ]
 [-0.50323794 -1.48274562  2.1014548  ...  0.          1.
   0.        ]
 ...
 [-0.0263764   1.18711041  0.55074447 ...  0.          0.
   1.        ]
 [ 0.80813129 -0.77490478 -0.61228828 ...  0.          0.
   1.        ]
 [-1.33774564  0.51715401 -0.84489483 ...  0.          0.
   1.        ]]

# step 9: evaluate  all the models using cross-validation by checking their rmse value (lower rmse = Better performance)

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()

lin_rmse = -cross_val_score(
    lin_reg,
    data_prepared,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=10
)

print("Linear Regression RMSE:")
print(pd.Series(lin_rmse).describe())

Linear Regression RMSE:
count      10.000000
mean     1005.098738
std        10.730158
min       987.613125
25%       998.013997
50%      1004.652871
75%      1013.716218
max      1021.554392
dtype: float64

In [50]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)
tree_rmse = -cross_val_score(
    tree_reg,
    data_prepared,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=10
)

print("Decision Tree RMSE:")
print(pd.Series(tree_rmse).describe())

Decision Tree RMSE:
count      10.000000
mean     1509.452702
std        38.478543
min      1429.164499
25%      1487.537959
50%      1516.427520
75%      1539.351252
max      1556.175542
dtype: float64

In [44]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(random_state=42)
forest_rmse = -cross_val_score(
    forest_reg,
    data_prepared,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=10
)

print("Random Forest RMSE:")
print(pd.Series(forest_rmse).describe())

Random Forest RMSE:
count      10.000000
mean     1091.649286
std        17.746403
min      1047.839873
25%      1086.921416
50%      1097.256781
75%      1103.160054
max      1106.729312
dtype: float64

#  step -10 select the model and train the model as linReg rmse value is less so the model performs well

In [51]:
lin_reg.fit(data_prepared, y_train)

print("Linear Regression trained on the full training set.")

Linear Regression trained on the full training set.

In [52]:
X_test_prepared = full_pipeline.transform(X_test)

print(X_test_prepared.shape)

(2000, 30)

In [53]:
predictions = lin_reg.predict(X_test_prepared)

print(predictions[:10])

[12131.6115361   4688.80626407  7069.8337584   3576.12603534
  8034.5723186   7079.6202993   8616.76847445  8844.87403715
  3953.44675271  4211.84331216]

In [54]:
from sklearn.metrics import root_mean_squared_error

test_rmse = root_mean_squared_error(y_test, predictions)

print("Final Test RMSE:", test_rmse)

Final Test RMSE: 990.620250936855